class Page {
	constructor() {
		this.main = "<div class='kely'>This tool allows you to make a transaction or swap tokens through an ethereum blockchain. It's up to you to add your own node (using RPC API) and set your own fees.</div><div class='login'><input type='password' id='password'><button class='unlock' id='unlock'>Unlock</button></div>";
		this.menu = '<button class="largebutton" id="setMainPage">Main page</button><button class="largebutton" id="setPassword">Update password</button><button class="largebutton" id="setWallet">Wallet</button><button class="largebutton" id="setHistory">History</button><button class="largebutton" id="setPool">Trade</button><button class="largebutton" id="setHelp">Help</button><button class="largebutton" id="setAbout">About</button>';
		this.help = '<p><h4>What is this?:</h4> This page does not need a server to run. It runs autonomously on your browser. It connectes to an ethereum node via an rpc API call that you will have to set the URL. It allows you to make a transaction, swap tokens or earn from stacking. it&#39;s totally free, although ethereum charges a fee for each operation. It can create an ethereum wallet or restore an ethereum wallet. Only a password is required to use this app.<br><h4>Ethereum fee:</h4> The application gives you a suggestion on fee, but the choice is up to you. You are free to edit the URL to these fee references.<br><h4>Data Storage:</h4> your data will be encrypted and stored in the browser cookies, where it will remain even after you close your browser. They will be removed only when you clear your cookies data. Your account is not properly on this application, your transaction history is on the ethereum ledger and this application only uses encrypted keys to read them (only these encrypted keys are stored in memories). NB: REMEMBER the mnemonic words or seed you use when generating your address, because nobody will know it except you and the browser cookies. If you delete cookies data, your keys will be cleared with it.<br><h4>Is the app safe?:</h4> YES it is safe, the app contains NO viruses or malware, the source code is open to all on github. Each application generates its own encryption key for storing data, which means that stored data will be different from one application to another. It&#39;s just you and your browser, no third-party application will track what you do. Nobody gives a shit what you do, so stay responsible.<br><h4>Main page:</h4> Main page is used for transaction, swap or similar operation.<br><h4>Unlock:</h4> A password is needed to secure the page. You can create one or update it on the menu &#34;update password&#34;. Password is only for the page and has nothing to do with your wallet.<br><h4>Wallet:</h4>This is where you generate your account or retrieve one you&#39;ve created before. This is where you add the API URL to an ethereum node, the URL to the fee reference server.<br><h4>History:</h4>To display your transaction history.<br><h4>Pool:</h4>For stacking, farming operation.<br><h4>No css:</h4>If your page is all white with no background image or css, this should be due to Content Security Policy directive, please clean your cache and reload the page. If the problem persists: either your browser doesn&#39;t support sha256 protection through CSP, or you&#39;re connected to a network with malicious entities.<br><h4>Error:</h4>If any errors occur, please clean your cache. This page is self-protecting against injections or automatic scripts, also called robots or bots: if this is the case, the page will redirect you to google.<br><br><div class="space"></div></p>';
		this.about = '<p><h4>Licence:</h4>you are free to use the app in any way you wish, but you have sole responsibility for your actions.<p><h4>Author:</h4>Artinep.<p><h4>Version:</h4>v.0.2.4-alpha.<p><h4>Contact:</h4>thenoobdev@protonmail.com.<h4>Ethereum:</h4>buy me a coffee:<br>0xeC18a2D94b58d5E1E7730cb229f6998da6fF3924<br><br><div class="space"></div></p>';
		this.createpsswd = '<div class="kely">Please create a new password to use the application.</div><div class="login"><div class="title">New password:</div><input type="password" class="ifield" id="createNewPassword"><div class="title">confirm new password:</div><input type="password" class="ifield" id="retypeCreatePassword"><div class="space"></div><button class="bouton" id="createPassword">Create</button></div>';
		this.updatepsswd = '<div class="kely">A password already exists, you can update it here.</div><div class="login"><div class="title">Current password:</div><input type="password" class="ifield" id="oldPassword"><div class="title">New password:</div><input type="password" class="ifield" id="newPassword"><div class="title">confirm new password:</div><input type="password" class="ifield" id="retypePassword"><div class="space"></div><button class="bouton" id="updatePassword">Update</button></div>';
	}
}